common:
  main_topic: go_server_topic
  client_prefix: client_
  session_prefix: session_
  message_types:
    data: "data:"
    config: "config:"

server:
  name: go_server
  # broker_address: tcp://192.168.0.66:1883
  broker_address: tcp://broker:1883

client:
  # broker_address: 192.168.0.66
  broker_address: localhost
  broker_port: 1883

session:
  # broker_address: 192.168.0.66
  broker_address: broker
  broker_port: 1883
  board_name_prefix: board_
